# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0002_beach_has_free_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='photo',
            field=models.ImageField(upload_to='beaches/media'),
        ),
    ]
