# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0003_auto_20180305_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='is_camping_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
