# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0004_beach_is_camping_friendly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beach',
            old_name='is_open_after_10pm',
            new_name='is_open_after_sunset',
        ),
    ]
