# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaches', '0005_auto_20180305_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='photo',
            field=models.ImageField(upload_to='beaches/static/media'),
        ),
    ]
